apiVersion: v1
kind: ServiceAccount
metadata:
  name: mesh-pinger-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mesh-pinger-cluster-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["list"] # Hardened: ONLY allowed to list pods, no create/delete access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mesh-pinger-crb
subjects:
  - kind: ServiceAccount
    name: mesh-pinger-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: mesh-pinger-cluster-role
  apiGroup: rbac.authorization.k8s.io