apiVersion: v1
kind: Pod
metadata:
  name: pinger-test
  labels:
    app: mesh-pinger # This label lets the pod find itself and others in the mesh
spec:
  containers:
  # Main applikation (what we are running health checks against)
  - name: main-app
    image: hashicorp/http-echo:latest
    args:
      - "-text=OK"
      - "-listen=:8081" 
    ports:
      - containerPort: 8081
  - name: pinger
    image: mesh-pinger:v3 #Uppdated to v3
    imagePullPolicy: Never 
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports:
      - containerPort: 8080
