apiVersion: v1
kind: Pod
metadata:
  name: pinger-test
  labels:
    app: mesh-pinger
spec:
  containers:
  - name: pinger
    image: mesh-pinger:v1
    # Detta är extremt viktigt: Vi säger åt K8s att INTE leta på internet,
    # utan använda bilden vi just laddade in manuellt.
    imagePullPolicy: Never 
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports:
      - containerPort: 8080
